### ISSUE TITLE
"How to publish" issues/proposals

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Guidance#4]
Broken bullet points (these require a blank line between the preceding text and the bullet points):
- [x] http://dev.iatistandard.org/how-to-publish/prepare-your-org/#create-your-project-team-and-or-iati-champion
- [x] http://dev.iatistandard.org/how-to-publish/establish-publishing-policies/#the-implementation-schedule

http://dev.iatistandard.org/how-to-publish/process-overview/
- [x] `:ref: 'prepare_your_org'` should be `:ref:`prepare_you_org``

http://dev.iatistandard.org/how-to-publish/prepare-your-org/
- [x] Put a table of contents at the top
- [x] Renumber so that there are not two number 9s
- [x] Update link for instructions on creating an IATI Organisation Identifier

http://dev.iatistandard.org/how-to-publish/establish-publishing-policies/
- [x] We should discuss namedropping of publishers in the context of this guidance - e.g. "unless the Publisher is a DFID grantee in which case it is mandatory"
- [x] "an explanation needs to be provided on how the units of aid are split between the hierarchy levels." where should this explanation be provided? There's a few other similar sentences on the page, but this one stands out because it's described as something publishers "need" to do. Now in: https://github.com/IATI/IATI-Guidance/issues/27
- [x] Paragraph beginning "It is also important to differentiate what data will appear at the different levels. " needs to be compared to the proposal/guidance at http://support.iatistandard.org/entries/40759343-General-rules-for-multi-level-reporting: https://github.com/IATI/IATI-Guidance/issues/27
- [x] "IATI Licensing Standard" - this is not linked to or explained. Is it the same as the Open Aid Information (OAI) Licensing Standard?: https://github.com/IATI/IATI-Guidance/issues/35
- [x] "Open Aid Information Licensing Standard" - This feels like it could do with its own page: https://github.com/IATI/IATI-Guidance/issues/35
- [x] Headings are missing for "Element....." - lack of these makes the section hard to read. Ben
- [x] Formatting is missing compared to http://iatistandard.org/getting-started/licencing/licensing-your-iati-data/
- [x] Footnotes could be converted to proper footnote formatting
- [x] typos "do you included transactions" "on their ‘s own" "If you have decided to create an IATI specific web page you might decide that it should include links to your IATI files?" "5. The TAG sceretariat"

http://dev.iatistandard.org/how-to-publish/select-data-to-publish/
- [x] typo "security of confidentiality"

http://dev.iatistandard.org/how-to-publish/select-publishing-tool/
- [ ] "There are currently three different mechanisms available" -> we might not want to recommend them, but there are other mechanisms.
- [x] "Aidstream (www.aidstream.org)" should this be a link?
- [x] http://www.csv2iati.iatistandard.org/ should be http://csv2iati.iatistandard.org/
- [x] typo "proves more cost effective means"

http://dev.iatistandard.org/how-to-publish/publish-files/
- [x] "(see 3.6)" - not sure what this means
- [x] missing terminal full stops
- [x] Question marks - "(still?)" "to be authorised?" - are these meant to be part of the text?
- [x] typos "it is" "publishner_name" "datafiles details" "a CSV files"
