### ISSUE TITLE
Guidance topics to write

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Guidance#9]
Moving issues over from: https://github.com/IATI/IATI-Extra-Documentation/issues/52
## ORGANISATION / PROCESS RELATED
- [x] Changing your organisation name
- [x] Describing multiple orgs in org file
- [x] Implementation Schedules
- [x] About secondary publishing
## PUBLISHING RELATED
- [x] what's the difference between `reporting-org` and Publisher? https://github.com/IATI/IATI-Extra-Documentation/issues/16
- [x] updating activities over time https://github.com/IATI/IATI-Extra-Documentation/issues/46
- [x] segmenting files - good practice
- [x] URL construction (data.domain or domain/data etc)
- [x] Advice for publishers about HTTPS: https://github.com/IATI/IATI-Extra-Documentation/issues/41
- [x] spaces in file names: https://github.com/IATI/IATI-Extra-Documentation/issues/35
- [x] activities in more than one file: https://github.com/IATI/IATI-Extra-Documentation/issues/54
## TECHNICAL RELATED
- [x] Add general dates guidance: https://github.com/IATI/IATI-Extra-Documentation/issues/38
- [x] Globally unique identifiers: https://github.com/IATI/IATI-Extra-Documentation/issues/45
- [x] structure of identifiers: https://github.com/IATI/IATI-Extra-Documentation/issues/39 
- [x] Capitalisation: https://github.com/IATI/IATI-Extra-Documentation/issues/63
## IN DEPTH 
- [x] working out percentage splits for sector and countries
- [x] using RO vocabulary, and pointing people to it
- [x] using namespace extensions
- [x] revising budgets  - keep original?
- [x] capital spend - budget / commitment?
- [x] country-budget-items - must add up to 100%
- [x] dealing with imprecise dates
- [x] language use for freetext / names in elements
